#if !canImport(ObjectiveC)
import XCTest

extension AccountTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AccountTests = [
        ("testAccountParsedProperly", testAccountParsedProperly),
    ]
}

extension ApplicationFeeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ApplicationFeeTests = [
        ("testApplicationFeeParsesProperly", testApplicationFeeParsesProperly),
        ("testApplicationFeeRefundParsesProperly", testApplicationFeeRefundParsesProperly),
    ]
}

extension BalanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BalanceTests = [
        ("testBalanceParsedProperly", testBalanceParsedProperly),
        ("testBalanceTransactionParsedProperly", testBalanceTransactionParsedProperly),
    ]
}

extension ChargeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChargeTests = [
        ("testChargeParsedProperly", testChargeParsedProperly),
    ]
}

extension CountrySpecTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CountrySpecTests = [
        ("testCountrySpecParsesProperly", testCountrySpecParsesProperly),
    ]
}

extension CustomerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CustomerTests = [
        ("testCustomerParsedProperly", testCustomerParsedProperly),
    ]
}

extension DisputeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DisputeTests = [
        ("testDisputeParsedProperly", testDisputeParsedProperly),
    ]
}

extension EphemeralKeyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EphemeralKeyTests = [
        ("testEphemeralKeyParsedProperly", testEphemeralKeyParsedProperly),
    ]
}

extension ErrorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ErrorTests = [
        ("testErrorParsedProperly", testErrorParsedProperly),
    ]
}

extension FileTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FileTests = [
        ("testFileLinkParsedProperly", testFileLinkParsedProperly),
        ("testFileUploadParsedProperly", testFileUploadParsedProperly),
    ]
}

extension InvoiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InvoiceTests = [
        ("testInvoiceItemParsedProperly", testInvoiceItemParsedProperly),
        ("testInvoiceParsedProperly", testInvoiceParsedProperly),
    ]
}

extension OrderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__OrderTests = [
        ("testOrderIsProperlyParsed", testOrderIsProperlyParsed),
    ]
}

extension PaymentSourceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PaymentSourceTests = [
        ("testSourceListIsProperlyParsed", testSourceListIsProperlyParsed),
    ]
}

extension PayoutTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PayoutTests = [
        ("testPayoutsParsedProperly", testPayoutsParsedProperly),
    ]
}

extension ProductTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ProductTests = [
        ("testProductParsedProperly", testProductParsedProperly),
    ]
}

extension QueryEncodingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QueryEncodingTests = [
        ("testNestedArrayQueryEncodedProperly", testNestedArrayQueryEncodedProperly),
        ("testNestedDictionaryQueryEncodedProperly", testNestedDictionaryQueryEncodedProperly),
        ("testSimpleQueryEncodedProperly", testSimpleQueryEncodedProperly),
    ]
}

extension RefundTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RefundTests = [
        ("testRefundParsedProperly", testRefundParsedProperly),
    ]
}

extension ReviewTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ReviewTests = [
        ("testTopUpParsesProperly", testTopUpParsesProperly),
    ]
}

extension SKUTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SKUTests = [
        ("testSkuParsedProperly", testSkuParsedProperly),
    ]
}

extension SourceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SourceTests = [
        ("testACHSourceParsedProperly", testACHSourceParsedProperly),
        ("testAlipaySourceParsedProperly", testAlipaySourceParsedProperly),
        ("testBancontactSourceParsedProperly", testBancontactSourceParsedProperly),
        ("testCardSourceParsedProperly", testCardSourceParsedProperly),
        ("testGiropaySourceParsedProperly", testGiropaySourceParsedProperly),
        ("testIdealSourceParsedProperly", testIdealSourceParsedProperly),
        ("testP24SourceParsedProperly", testP24SourceParsedProperly),
        ("testSepaDebitSourceParsedProperly", testSepaDebitSourceParsedProperly),
        ("testSofortSourceParsedProperly", testSofortSourceParsedProperly),
        ("testThreeDSecureSourceParsedProperly", testThreeDSecureSourceParsedProperly),
    ]
}

extension SubscriptionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SubscriptionTests = [
        ("testSubscriptionParsedProperly", testSubscriptionParsedProperly),
    ]
}

extension TokenTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TokenTests = [
        ("testBankTokenParsedProperly", testBankTokenParsedProperly),
        ("testCardTokenParsedProperly", testCardTokenParsedProperly),
    ]
}

extension TopUpTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TopUpTests = [
        ("testTopUpParsesProperly", testTopUpParsesProperly),
    ]
}

extension TransferTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TransferTests = [
        ("testTransferParsedProperly", testTransferParsedProperly),
    ]
}

extension ValueListItemTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ValueListItemTests = [
        ("testValueListItemarsesProperly", testValueListItemarsesProperly),
    ]
}

extension ValueListTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ValueListTests = [
        ("testValueListItemarsesProperly", testValueListItemarsesProperly),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AccountTests.__allTests__AccountTests),
        testCase(ApplicationFeeTests.__allTests__ApplicationFeeTests),
        testCase(BalanceTests.__allTests__BalanceTests),
        testCase(ChargeTests.__allTests__ChargeTests),
        testCase(CountrySpecTests.__allTests__CountrySpecTests),
        testCase(CustomerTests.__allTests__CustomerTests),
        testCase(DisputeTests.__allTests__DisputeTests),
        testCase(EphemeralKeyTests.__allTests__EphemeralKeyTests),
        testCase(ErrorTests.__allTests__ErrorTests),
        testCase(FileTests.__allTests__FileTests),
        testCase(InvoiceTests.__allTests__InvoiceTests),
        testCase(OrderTests.__allTests__OrderTests),
        testCase(PaymentSourceTests.__allTests__PaymentSourceTests),
        testCase(PayoutTests.__allTests__PayoutTests),
        testCase(ProductTests.__allTests__ProductTests),
        testCase(QueryEncodingTests.__allTests__QueryEncodingTests),
        testCase(RefundTests.__allTests__RefundTests),
        testCase(ReviewTests.__allTests__ReviewTests),
        testCase(SKUTests.__allTests__SKUTests),
        testCase(SourceTests.__allTests__SourceTests),
        testCase(SubscriptionTests.__allTests__SubscriptionTests),
        testCase(TokenTests.__allTests__TokenTests),
        testCase(TopUpTests.__allTests__TopUpTests),
        testCase(TransferTests.__allTests__TransferTests),
        testCase(ValueListItemTests.__allTests__ValueListItemTests),
        testCase(ValueListTests.__allTests__ValueListTests),
    ]
}
#endif
